---
- name: Install Jenkins, Java 11, and Maven on CentOS
  hosts: n1
  become: true
  tasks:
    - name: Install OpenJDK 11 on CentOS
      ansible.builtin.yum:
        name: java-11-openjdk-devel
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Download Jenkins GPG key
      ansible.builtin.get_url:
        url: "https://pkg.jenkins.io/redhat-stable/jenkins.io.key"
        dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-jenkins"
      when: "'CentOS' in ansible_distribution"

    - name: Set up Jenkins repository
      ansible.builtin.ini:
        path: /etc/yum.repos.d/jenkins.repo
        section: jenkins
        option: baseurl
        value: "http://pkg.jenkins.io/redhat-stable"
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Import Jenkins GPG key
      ansible.builtin.rpm_key:
        state: present
        key: RPM-GPG-KEY-jenkins
      when: "'CentOS' in ansible_distribution"

    - name: Install Jenkins on CentOS
      ansible.builtin.yum:
        name: jenkins
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install Maven on CentOS
      ansible.builtin.yum:
        name: maven
        state: present
      when: "'CentOS' in ansible_distribution"

  handlers:
    - name: Restart Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: restarted
...