---
- name: Install Jenkins, Java 11, and Maven on CentOS
  hosts: n1
  become: true
  tasks:
    - name: Install OpenJDK 11 on CentOS
      ansible.builtin.yum:
        name: java-11-openjdk-devel
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Ensure /etc/yum.repos.d directory exists
      ansible.builtin.file:
        path: /etc/yum.repos.d
        state: directory

    - name: Download Jenkins repository file
      ansible.builtin.get_url:
        url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
        dest: "/etc/yum.repos.d/jenkins.repo"
      when: "'CentOS' in ansible_distribution"

    - name: Import Jenkins GPG key
      ansible.builtin.command: 
        cmd: "rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key"
      when: "'CentOS' in ansible_distribution"

    - name: Install Jenkins on CentOS
      ansible.builtin.yum:
        name: jenkins
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Display Jenkins Initial Admin Password
      ansible.builtin.shell:
        cmd: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password
      when: "'CentOS' in ansible_distribution"

    - name: Display Jenkins Initial Admin Password Info
      ansible.builtin.debug:
        var: jenkins_initial_password.stdout_lines
      when: "'CentOS' in ansible_distribution"

    - name: Install Maven on CentOS
      ansible.builtin.yum:
        name: maven
        state: present
      when: "'CentOS' in ansible_distribution"

  handlers:
    - name: Restart Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: restarted
...