---
- name: Install Jenkins, Java 11, and Maven on CentOS
  hosts: n1
  become: true
  tasks:
    - name: Install OpenJDK 11 on CentOS
      ansible.builtin.yum:
        name: java-11-openjdk-devel
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Download Jenkins repository file
      ansible.builtin.command: 
        cmd: "wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo"
      when: "'CentOS' in ansible_distribution"

    - name: Import Jenkins GPG key
      ansible.builtin.command: 
        cmd: "rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key"
      when: "'CentOS' in ansible_distribution"

    - name: Install Jenkins on CentOS
      ansible.builtin.yum:
        name: jenkins
        state: present
      when: "'CentOS' in ansible_distribution"

    - name: Install Maven on CentOS
      ansible.builtin.yum:
        name: maven
        state: present
      when: "'CentOS' in ansible_distribution"

  handlers:
    - name: Restart Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: restarted
...